#ifndef CUDA_COMMON_H
#define CUDA_COMMON_H

// THREADS BLOCK
#define BLOCK_DIM1D 256
#define BLOCK_DIM1D_LARGE 512

// MAX THREADS PER STREAM
#define MAXTHREADS_STREAM 65536

#endif // CUDA_COMMON_H
