/*
     Copyright (C) 2012  GP-you Group (http://gp-you.org)
 
     This program is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.
 
     This program is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.
 
     You should have received a copy of the GNU General Public License
     along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#define EXPF_KERNEL  expf_kernel
#define S_EXPF_KERNEL  "expf_kernel"
#define N_EXPF_KERNEL 0
#define EXPC_KERNEL  expc_kernel
#define S_EXPC_KERNEL  "expc_kernel"
#define N_EXPC_KERNEL 1
#define EXPD_KERNEL  expd_kernel
#define S_EXPD_KERNEL  "expd_kernel"
#define N_EXPD_KERNEL 2
#define EXPCD_KERNEL  expcd_kernel
#define S_EXPCD_KERNEL  "expcd_kernel"
#define N_EXPCD_KERNEL 3
#define N_EXPI_KERNEL -1
//
#define SQRTF_KERNEL  sqrtf_kernel
#define S_SQRTF_KERNEL  "sqrtf_kernel"
#define N_SQRTF_KERNEL 4
#define N_SQRTC_KERNEL -1
#define SQRTD_KERNEL  sqrtd_kernel
#define S_SQRTD_KERNEL  "sqrtd_kernel"
#define N_SQRTD_KERNEL 5
#define N_SQRTCD_KERNEL -1
#define N_SQRTI_KERNEL -1
//
#define LOGF_KERNEL  logf_kernel
#define S_LOGF_KERNEL  "logf_kernel"
#define N_LOGF_KERNEL 6
#define LOGC_KERNEL  logc_kernel
#define S_LOGC_KERNEL  "logc_kernel"
#define N_LOGC_KERNEL 7
#define LOGD_KERNEL  logd_kernel
#define S_LOGD_KERNEL  "logd_kernel"
#define N_LOGD_KERNEL 8
#define LOGCD_KERNEL  logcd_kernel
#define S_LOGCD_KERNEL  "logcd_kernel"
#define N_LOGCD_KERNEL 9
#define N_LOGI_KERNEL -1
//
#define LOG2F_KERNEL  log2f_kernel
#define S_LOG2F_KERNEL  "log2f_kernel"
#define N_LOG2F_KERNEL 10
#define N_LOG2C_KERNEL -1
#define LOG2D_KERNEL  log2d_kernel
#define S_LOG2D_KERNEL  "log2d_kernel"
#define N_LOG2D_KERNEL 11
#define N_LOG2CD_KERNEL -1
#define N_LOG2I_KERNEL -1
//
#define LOG10F_KERNEL  log10f_kernel
#define S_LOG10F_KERNEL  "log10f_kernel"
#define N_LOG10F_KERNEL 12
#define LOG10C_KERNEL  log10c_kernel
#define S_LOG10C_KERNEL  "log10c_kernel"
#define N_LOG10C_KERNEL 13
#define LOG10D_KERNEL  log10d_kernel
#define S_LOG10D_KERNEL  "log10d_kernel"
#define N_LOG10D_KERNEL 14
#define LOG10CD_KERNEL  log10cd_kernel
#define S_LOG10CD_KERNEL  "log10cd_kernel"
#define N_LOG10CD_KERNEL 15
#define N_LOG10I_KERNEL -1
//
#define LOG1PF_KERNEL  log1pf_kernel
#define S_LOG1PF_KERNEL  "log1pf_kernel"
#define N_LOG1PF_KERNEL 16
#define N_LOG1PC_KERNEL -1
#define LOG1PD_KERNEL  log1pd_kernel
#define S_LOG1PD_KERNEL  "log1pd_kernel"
#define N_LOG1PD_KERNEL 17
#define N_LOG1PCD_KERNEL -1
#define N_LOG1PI_KERNEL -1
//
#define SINF_KERNEL  sinf_kernel
#define S_SINF_KERNEL  "sinf_kernel"
#define N_SINF_KERNEL 18
#define N_SINC_KERNEL -1
#define SIND_KERNEL  sind_kernel
#define S_SIND_KERNEL  "sind_kernel"
#define N_SIND_KERNEL 19
#define N_SINCD_KERNEL -1
#define N_SINI_KERNEL -1
//
#define COSF_KERNEL  cosf_kernel
#define S_COSF_KERNEL  "cosf_kernel"
#define N_COSF_KERNEL 20
#define N_COSC_KERNEL -1
#define COSD_KERNEL  cosd_kernel
#define S_COSD_KERNEL  "cosd_kernel"
#define N_COSD_KERNEL 21
#define N_COSCD_KERNEL -1
#define N_COSI_KERNEL -1
//
#define TANF_KERNEL  tanf_kernel
#define S_TANF_KERNEL  "tanf_kernel"
#define N_TANF_KERNEL 22
#define N_TANC_KERNEL -1
#define TAND_KERNEL  tand_kernel
#define S_TAND_KERNEL  "tand_kernel"
#define N_TAND_KERNEL 23
#define N_TANCD_KERNEL -1
#define N_TANI_KERNEL -1
//
#define ASINF_KERNEL  asinf_kernel
#define S_ASINF_KERNEL  "asinf_kernel"
#define N_ASINF_KERNEL 24
#define N_ASINC_KERNEL -1
#define ASIND_KERNEL  asind_kernel
#define S_ASIND_KERNEL  "asind_kernel"
#define N_ASIND_KERNEL 25
#define N_ASINCD_KERNEL -1
#define N_ASINI_KERNEL -1
//
#define ACOSF_KERNEL  acosf_kernel
#define S_ACOSF_KERNEL  "acosf_kernel"
#define N_ACOSF_KERNEL 26
#define N_ACOSC_KERNEL -1
#define ACOSD_KERNEL  acosd_kernel
#define S_ACOSD_KERNEL  "acosd_kernel"
#define N_ACOSD_KERNEL 27
#define N_ACOSCD_KERNEL -1
#define N_ACOSI_KERNEL -1
//
#define ATANF_KERNEL  atanf_kernel
#define S_ATANF_KERNEL  "atanf_kernel"
#define N_ATANF_KERNEL 28
#define N_ATANC_KERNEL -1
#define ATAND_KERNEL  atand_kernel
#define S_ATAND_KERNEL  "atand_kernel"
#define N_ATAND_KERNEL 29
#define N_ATANCD_KERNEL -1
#define N_ATANI_KERNEL -1
//
#define SINHF_KERNEL  sinhf_kernel
#define S_SINHF_KERNEL  "sinhf_kernel"
#define N_SINHF_KERNEL 30
#define N_SINHC_KERNEL -1
#define SINHD_KERNEL  sinhd_kernel
#define S_SINHD_KERNEL  "sinhd_kernel"
#define N_SINHD_KERNEL 31
#define N_SINHCD_KERNEL -1
#define N_SINHI_KERNEL -1
//
#define COSHF_KERNEL  coshf_kernel
#define S_COSHF_KERNEL  "coshf_kernel"
#define N_COSHF_KERNEL 32
#define N_COSHC_KERNEL -1
#define COSHD_KERNEL  coshd_kernel
#define S_COSHD_KERNEL  "coshd_kernel"
#define N_COSHD_KERNEL 33
#define N_COSHCD_KERNEL -1
#define N_COSHI_KERNEL -1
//
#define TANHF_KERNEL  tanhf_kernel
#define S_TANHF_KERNEL  "tanhf_kernel"
#define N_TANHF_KERNEL 34
#define N_TANHC_KERNEL -1
#define TANHD_KERNEL  tanhd_kernel
#define S_TANHD_KERNEL  "tanhd_kernel"
#define N_TANHD_KERNEL 35
#define N_TANHCD_KERNEL -1
#define N_TANHI_KERNEL -1
//
#define ASINHF_KERNEL  asinhf_kernel
#define S_ASINHF_KERNEL  "asinhf_kernel"
#define N_ASINHF_KERNEL 36
#define N_ASINHC_KERNEL -1
#define ASINHD_KERNEL  asinhd_kernel
#define S_ASINHD_KERNEL  "asinhd_kernel"
#define N_ASINHD_KERNEL 37
#define N_ASINHCD_KERNEL -1
#define N_ASINHI_KERNEL -1
//
#define ACOSHF_KERNEL  acoshf_kernel
#define S_ACOSHF_KERNEL  "acoshf_kernel"
#define N_ACOSHF_KERNEL 38
#define N_ACOSHC_KERNEL -1
#define ACOSHD_KERNEL  acoshd_kernel
#define S_ACOSHD_KERNEL  "acoshd_kernel"
#define N_ACOSHD_KERNEL 39
#define N_ACOSHCD_KERNEL -1
#define N_ACOSHI_KERNEL -1
//
#define ATANHF_KERNEL  atanhf_kernel
#define S_ATANHF_KERNEL  "atanhf_kernel"
#define N_ATANHF_KERNEL 40
#define N_ATANHC_KERNEL -1
#define ATANHD_KERNEL  atanhd_kernel
#define S_ATANHD_KERNEL  "atanhd_kernel"
#define N_ATANHD_KERNEL 41
#define N_ATANHCD_KERNEL -1
#define N_ATANHI_KERNEL -1
//
#define ROUNDF_KERNEL  roundf_kernel
#define S_ROUNDF_KERNEL  "roundf_kernel"
#define N_ROUNDF_KERNEL 42
#define N_ROUNDC_KERNEL -1
#define ROUNDD_KERNEL  roundd_kernel
#define S_ROUNDD_KERNEL  "roundd_kernel"
#define N_ROUNDD_KERNEL 43
#define N_ROUNDCD_KERNEL -1
#define N_ROUNDI_KERNEL -1
//
#define CEILF_KERNEL  ceilf_kernel
#define S_CEILF_KERNEL  "ceilf_kernel"
#define N_CEILF_KERNEL 44
#define N_CEILC_KERNEL -1
#define CEILD_KERNEL  ceild_kernel
#define S_CEILD_KERNEL  "ceild_kernel"
#define N_CEILD_KERNEL 45
#define N_CEILCD_KERNEL -1
#define N_CEILI_KERNEL -1
//
#define FLOORF_KERNEL  floorf_kernel
#define S_FLOORF_KERNEL  "floorf_kernel"
#define N_FLOORF_KERNEL 46
#define N_FLOORC_KERNEL -1
#define FLOORD_KERNEL  floord_kernel
#define S_FLOORD_KERNEL  "floord_kernel"
#define N_FLOORD_KERNEL 47
#define N_FLOORCD_KERNEL -1
#define N_FLOORI_KERNEL -1
//
#define ABSF_KERNEL  absf_kernel
#define S_ABSF_KERNEL  "absf_kernel"
#define N_ABSF_KERNEL 48
#define ABSC_KERNEL  absc_kernel
#define S_ABSC_KERNEL  "absc_kernel"
#define N_ABSC_KERNEL 49
#define ABSD_KERNEL  absd_kernel
#define S_ABSD_KERNEL  "absd_kernel"
#define N_ABSD_KERNEL 50
#define ABSCD_KERNEL  abscd_kernel
#define S_ABSCD_KERNEL  "abscd_kernel"
#define N_ABSCD_KERNEL 51
#define N_ABSI_KERNEL -1
//
#define ZEROSF_KERNEL  zerosf_kernel
#define S_ZEROSF_KERNEL  "zerosf_kernel"
#define N_ZEROSF_KERNEL 52
#define ZEROSC_KERNEL  zerosc_kernel
#define S_ZEROSC_KERNEL  "zerosc_kernel"
#define N_ZEROSC_KERNEL 53
#define ZEROSD_KERNEL  zerosd_kernel
#define S_ZEROSD_KERNEL  "zerosd_kernel"
#define N_ZEROSD_KERNEL 54
#define ZEROSCD_KERNEL  zeroscd_kernel
#define S_ZEROSCD_KERNEL  "zeroscd_kernel"
#define N_ZEROSCD_KERNEL 55
#define N_ZEROSI_KERNEL -1
//
#define ONESF_KERNEL  onesf_kernel
#define S_ONESF_KERNEL  "onesf_kernel"
#define N_ONESF_KERNEL 56
#define ONESC_KERNEL  onesc_kernel
#define S_ONESC_KERNEL  "onesc_kernel"
#define N_ONESC_KERNEL 57
#define ONESD_KERNEL  onesd_kernel
#define S_ONESD_KERNEL  "onesd_kernel"
#define N_ONESD_KERNEL 58
#define ONESCD_KERNEL  onescd_kernel
#define S_ONESCD_KERNEL  "onescd_kernel"
#define N_ONESCD_KERNEL 59
#define N_ONESI_KERNEL -1
//
#define UMINUSF_KERNEL  uminusf_kernel
#define S_UMINUSF_KERNEL  "uminusf_kernel"
#define N_UMINUSF_KERNEL 60
#define UMINUSC_KERNEL  uminusc_kernel
#define S_UMINUSC_KERNEL  "uminusc_kernel"
#define N_UMINUSC_KERNEL 61
#define UMINUSD_KERNEL  uminusd_kernel
#define S_UMINUSD_KERNEL  "uminusd_kernel"
#define N_UMINUSD_KERNEL 62
#define UMINUSCD_KERNEL  uminuscd_kernel
#define S_UMINUSCD_KERNEL  "uminuscd_kernel"
#define N_UMINUSCD_KERNEL 63
#define N_UMINUSI_KERNEL -1
//
#define CONJUGATEF_KERNEL  conjugatef_kernel
#define S_CONJUGATEF_KERNEL  "conjugatef_kernel"
#define N_CONJUGATEF_KERNEL 64
#define CONJUGATEC_KERNEL  conjugatec_kernel
#define S_CONJUGATEC_KERNEL  "conjugatec_kernel"
#define N_CONJUGATEC_KERNEL 65
#define CONJUGATED_KERNEL  conjugated_kernel
#define S_CONJUGATED_KERNEL  "conjugated_kernel"
#define N_CONJUGATED_KERNEL 66
#define CONJUGATECD_KERNEL  conjugatecd_kernel
#define S_CONJUGATECD_KERNEL  "conjugatecd_kernel"
#define N_CONJUGATECD_KERNEL 67
#define N_CONJUGATEI_KERNEL -1
//
#define NOTF_KERNEL  notf_kernel
#define S_NOTF_KERNEL  "notf_kernel"
#define N_NOTF_KERNEL 68
#define N_NOTC_KERNEL -1
#define NOTD_KERNEL  notd_kernel
#define S_NOTD_KERNEL  "notd_kernel"
#define N_NOTD_KERNEL 69
#define N_NOTCD_KERNEL -1
#define N_NOTI_KERNEL -1
//
#define TRANSPOSEF_KERNEL  transposef_kernel
#define S_TRANSPOSEF_KERNEL  "transposef_kernel"
#define N_TRANSPOSEF_KERNEL 70
#define TRANSPOSEF_TEX_KERNEL  transposef_tex_kernel
#define S_TRANSPOSEF_TEX_KERNEL  "transposef_tex_kernel"
#define N_TRANSPOSEF_TEX_KERNEL 71
#define TRANSPOSEC_TEX_KERNEL  transposec_tex_kernel
#define S_TRANSPOSEC_TEX_KERNEL  "transposec_tex_kernel"
#define N_TRANSPOSEC_TEX_KERNEL 72
#define TRANSPOSED_TEX_KERNEL  transposed_tex_kernel
#define S_TRANSPOSED_TEX_KERNEL  "transposed_tex_kernel"
#define N_TRANSPOSED_TEX_KERNEL 73
#define TRANSPOSECD_TEX_KERNEL  transposecd_tex_kernel
#define S_TRANSPOSECD_TEX_KERNEL  "transposecd_tex_kernel"
#define N_TRANSPOSECD_TEX_KERNEL 74
#define N_TRANSPOSEI_TEX_KERNEL -1
//
#define PACKFC2C_KERNEL  packfC2C_kernel
#define S_PACKFC2C_KERNEL  "packfC2C_kernel"
#define N_PACKFC2C_KERNEL 75
#define PACKDC2C_KERNEL  packdC2C_kernel
#define S_PACKDC2C_KERNEL  "packdC2C_kernel"
#define N_PACKDC2C_KERNEL 76
#define N_PACKIC2C_KERNEL -1
#define UNPACKFC2C_KERNEL  unpackfC2C_kernel
#define S_UNPACKFC2C_KERNEL  "unpackfC2C_kernel"
#define N_UNPACKFC2C_KERNEL 77
#define UNPACKDC2C_KERNEL  unpackdC2C_kernel
#define S_UNPACKDC2C_KERNEL  "unpackdC2C_kernel"
#define N_UNPACKDC2C_KERNEL 78
#define N_UNPACKIC2C_KERNEL -1
//
#define SUBSINDEXF_KERNEL  subsindexf_kernel
#define S_SUBSINDEXF_KERNEL  "subsindexf_kernel"
#define N_SUBSINDEXF_KERNEL 79
#define SUBSINDEXC_KERNEL  subsindexc_kernel
#define S_SUBSINDEXC_KERNEL  "subsindexc_kernel"
#define N_SUBSINDEXC_KERNEL 80
#define SUBSINDEXD_KERNEL  subsindexd_kernel
#define S_SUBSINDEXD_KERNEL  "subsindexd_kernel"
#define N_SUBSINDEXD_KERNEL 81
#define SUBSINDEXCD_KERNEL  subsindexcd_kernel
#define S_SUBSINDEXCD_KERNEL  "subsindexcd_kernel"
#define N_SUBSINDEXCD_KERNEL 82
//
#define SUBSINDEX1F_KERNEL  subsindex1f_kernel
#define S_SUBSINDEX1F_KERNEL  "subsindex1f_kernel"
#define N_SUBSINDEX1F_KERNEL 83
#define SUBSINDEX1C_KERNEL  subsindex1c_kernel
#define S_SUBSINDEX1C_KERNEL  "subsindex1c_kernel"
#define N_SUBSINDEX1C_KERNEL 84
#define SUBSINDEX1D_KERNEL  subsindex1d_kernel
#define S_SUBSINDEX1D_KERNEL  "subsindex1d_kernel"
#define N_SUBSINDEX1D_KERNEL 85
#define SUBSINDEX1CD_KERNEL  subsindex1cd_kernel
#define S_SUBSINDEX1CD_KERNEL  "subsindex1cd_kernel"
#define N_SUBSINDEX1CD_KERNEL 86
//
#define PERMSUBSINDEX1F_KERNEL  permsubsindex1f_kernel
#define S_PERMSUBSINDEX1F_KERNEL  "permsubsindex1f_kernel"
#define N_PERMSUBSINDEX1F_KERNEL 87
#define PERMSUBSINDEX1C_KERNEL  permsubsindex1c_kernel
#define S_PERMSUBSINDEX1C_KERNEL  "permsubsindex1c_kernel"
#define N_PERMSUBSINDEX1C_KERNEL 88
#define PERMSUBSINDEX1D_KERNEL  permsubsindex1d_kernel
#define S_PERMSUBSINDEX1D_KERNEL  "permsubsindex1d_kernel"
#define N_PERMSUBSINDEX1D_KERNEL 89
#define PERMSUBSINDEX1CD_KERNEL  permsubsindex1cd_kernel
#define S_PERMSUBSINDEX1CD_KERNEL  "permsubsindex1cd_kernel"
#define N_PERMSUBSINDEX1CD_KERNEL 90
//
#define SUMF_TEX_KERNEL  sumf_tex_kernel
#define S_SUMF_TEX_KERNEL  "sumf_tex_kernel"
#define N_SUMF_TEX_KERNEL 91
#define SUMC_TEX_KERNEL  sumc_tex_kernel
#define S_SUMC_TEX_KERNEL  "sumc_tex_kernel"
#define N_SUMC_TEX_KERNEL 92
#define SUMD_TEX_KERNEL  sumd_tex_kernel
#define S_SUMD_TEX_KERNEL  "sumd_tex_kernel"
#define N_SUMD_TEX_KERNEL 93
#define SUMCD_TEX_KERNEL  sumcd_tex_kernel
#define S_SUMCD_TEX_KERNEL  "sumcd_tex_kernel"
#define N_SUMCD_TEX_KERNEL 94
#define SUMF_KERNEL  sumf_kernel
#define S_SUMF_KERNEL  "sumf_kernel"
#define N_SUMF_KERNEL 95
#define SUM1F_TEX_KERNEL  sum1f_tex_kernel
#define S_SUM1F_TEX_KERNEL  "sum1f_tex_kernel"
#define N_SUM1F_TEX_KERNEL 96
//
#define COPYMEMORY_KERNEL  copymemory_kernel
#define S_COPYMEMORY_KERNEL  "copymemory_kernel"
#define N_COPYMEMORY_KERNEL 97
//
#define FILLVECTORF_KERNEL  fillVectorf_kernel
#define S_FILLVECTORF_KERNEL  "fillVectorf_kernel"
#define N_FILLVECTORF_KERNEL 98
#define FILLVECTORC_KERNEL  fillVectorc_kernel
#define S_FILLVECTORC_KERNEL  "fillVectorc_kernel"
#define N_FILLVECTORC_KERNEL 99
#define FILLVECTORD_KERNEL  fillVectord_kernel
#define S_FILLVECTORD_KERNEL  "fillVectord_kernel"
#define N_FILLVECTORD_KERNEL 100
#define FILLVECTORCD_KERNEL  fillVectorcd_kernel
#define S_FILLVECTORCD_KERNEL  "fillVectorcd_kernel"
#define N_FILLVECTORCD_KERNEL 101
//
#define FILLVECTOR1F_KERNEL  fillVector1f_kernel
#define S_FILLVECTOR1F_KERNEL  "fillVector1f_kernel"
#define N_FILLVECTOR1F_KERNEL 102
#define FILLVECTOR1C_KERNEL  fillVector1c_kernel
#define S_FILLVECTOR1C_KERNEL  "fillVector1c_kernel"
#define N_FILLVECTOR1C_KERNEL 103
#define FILLVECTOR1D_KERNEL  fillVector1d_kernel
#define S_FILLVECTOR1D_KERNEL  "fillVector1d_kernel"
#define N_FILLVECTOR1D_KERNEL 104
#define FILLVECTOR1CD_KERNEL  fillVector1cd_kernel
#define S_FILLVECTOR1CD_KERNEL  "fillVector1cd_kernel"
#define N_FILLVECTOR1CD_KERNEL 105
//
#define FFTSYMMC_KERNEL  fftsymmc_kernel
#define S_FFTSYMMC_KERNEL  "fftsymmc_kernel"
#define N_FFTSYMMC_KERNEL 106
#define FFTSYMMCD_KERNEL  fftsymmcd_kernel
#define S_FFTSYMMCD_KERNEL  "fftsymmcd_kernel"
#define N_FFTSYMMCD_KERNEL 107
//
#define CHECKTEXTURE_KERNEL  checktexture_kernel
#define S_CHECKTEXTURE_KERNEL  "checktexture_kernel"
#define N_CHECKTEXTURE_KERNEL 108
//
#define REALIMAGF_KERNEL  realimagf_kernel
#define S_REALIMAGF_KERNEL  "realimagf_kernel"
#define N_REALIMAGF_KERNEL 109
#define REALIMAGD_KERNEL  realimagd_kernel
#define S_REALIMAGD_KERNEL  "realimagd_kernel"
#define N_REALIMAGD_KERNEL 110
//
#define FLOAT_TO_DOUBLE_KERNEL  float_to_double_kernel
#define S_FLOAT_TO_DOUBLE_KERNEL  "float_to_double_kernel"
#define N_FLOAT_TO_DOUBLE_KERNEL 111
#define FLOAT_TO_INTEGER_KERNEL  float_to_integer_kernel
#define S_FLOAT_TO_INTEGER_KERNEL  "float_to_integer_kernel"
#define N_FLOAT_TO_INTEGER_KERNEL 112
#define DOUBLE_TO_FLOAT_KERNEL  double_to_float_kernel
#define S_DOUBLE_TO_FLOAT_KERNEL  "double_to_float_kernel"
#define N_DOUBLE_TO_FLOAT_KERNEL 113
#define DOUBLE_TO_INTEGER_KERNEL  double_to_integer_kernel
#define S_DOUBLE_TO_INTEGER_KERNEL  "double_to_integer_kernel"
#define N_DOUBLE_TO_INTEGER_KERNEL 114
#define INTEGER_TO_FLOAT_KERNEL  integer_to_float_kernel
#define S_INTEGER_TO_FLOAT_KERNEL  "integer_to_float_kernel"
#define N_INTEGER_TO_FLOAT_KERNEL 115
#define INTEGER_TO_DOUBLE_KERNEL  integer_to_double_kernel
#define S_INTEGER_TO_DOUBLE_KERNEL  "integer_to_double_kernel"
#define N_INTEGER_TO_DOUBLE_KERNEL 116
//
#define PLUS_F_F_KERNEL  plus_f_f_kernel
#define S_PLUS_F_F_KERNEL  "plus_f_f_kernel"
#define N_PLUS_F_F_KERNEL 117
#define PLUS_F_C_KERNEL  plus_f_c_kernel
#define S_PLUS_F_C_KERNEL  "plus_f_c_kernel"
#define N_PLUS_F_C_KERNEL 118
#define PLUS_F_D_KERNEL  plus_f_d_kernel
#define S_PLUS_F_D_KERNEL  "plus_f_d_kernel"
#define N_PLUS_F_D_KERNEL 119
#define PLUS_F_CD_KERNEL  plus_f_cd_kernel
#define S_PLUS_F_CD_KERNEL  "plus_f_cd_kernel"
#define N_PLUS_F_CD_KERNEL 120
#define PLUS_C_F_KERNEL  plus_c_f_kernel
#define S_PLUS_C_F_KERNEL  "plus_c_f_kernel"
#define N_PLUS_C_F_KERNEL 121
#define PLUS_C_C_KERNEL  plus_c_c_kernel
#define S_PLUS_C_C_KERNEL  "plus_c_c_kernel"
#define N_PLUS_C_C_KERNEL 122
#define PLUS_C_D_KERNEL  plus_c_d_kernel
#define S_PLUS_C_D_KERNEL  "plus_c_d_kernel"
#define N_PLUS_C_D_KERNEL 123
#define PLUS_C_CD_KERNEL  plus_c_cd_kernel
#define S_PLUS_C_CD_KERNEL  "plus_c_cd_kernel"
#define N_PLUS_C_CD_KERNEL 124
#define PLUS_D_F_KERNEL  plus_d_f_kernel
#define S_PLUS_D_F_KERNEL  "plus_d_f_kernel"
#define N_PLUS_D_F_KERNEL 125
#define PLUS_D_C_KERNEL  plus_d_c_kernel
#define S_PLUS_D_C_KERNEL  "plus_d_c_kernel"
#define N_PLUS_D_C_KERNEL 126
#define PLUS_D_D_KERNEL  plus_d_d_kernel
#define S_PLUS_D_D_KERNEL  "plus_d_d_kernel"
#define N_PLUS_D_D_KERNEL 127
#define PLUS_D_CD_KERNEL  plus_d_cd_kernel
#define S_PLUS_D_CD_KERNEL  "plus_d_cd_kernel"
#define N_PLUS_D_CD_KERNEL 128
#define PLUS_CD_F_KERNEL  plus_cd_f_kernel
#define S_PLUS_CD_F_KERNEL  "plus_cd_f_kernel"
#define N_PLUS_CD_F_KERNEL 129
#define PLUS_CD_C_KERNEL  plus_cd_c_kernel
#define S_PLUS_CD_C_KERNEL  "plus_cd_c_kernel"
#define N_PLUS_CD_C_KERNEL 130
#define PLUS_CD_D_KERNEL  plus_cd_d_kernel
#define S_PLUS_CD_D_KERNEL  "plus_cd_d_kernel"
#define N_PLUS_CD_D_KERNEL 131
#define PLUS_CD_CD_KERNEL  plus_cd_cd_kernel
#define S_PLUS_CD_CD_KERNEL  "plus_cd_cd_kernel"
#define N_PLUS_CD_CD_KERNEL 132
//
#define TIMES_F_F_KERNEL  times_f_f_kernel
#define S_TIMES_F_F_KERNEL  "times_f_f_kernel"
#define N_TIMES_F_F_KERNEL 133
#define TIMES_F_C_KERNEL  times_f_c_kernel
#define S_TIMES_F_C_KERNEL  "times_f_c_kernel"
#define N_TIMES_F_C_KERNEL 134
#define TIMES_F_D_KERNEL  times_f_d_kernel
#define S_TIMES_F_D_KERNEL  "times_f_d_kernel"
#define N_TIMES_F_D_KERNEL 135
#define TIMES_F_CD_KERNEL  times_f_cd_kernel
#define S_TIMES_F_CD_KERNEL  "times_f_cd_kernel"
#define N_TIMES_F_CD_KERNEL 136
#define TIMES_C_F_KERNEL  times_c_f_kernel
#define S_TIMES_C_F_KERNEL  "times_c_f_kernel"
#define N_TIMES_C_F_KERNEL 137
#define TIMES_C_C_KERNEL  times_c_c_kernel
#define S_TIMES_C_C_KERNEL  "times_c_c_kernel"
#define N_TIMES_C_C_KERNEL 138
#define TIMES_C_D_KERNEL  times_c_d_kernel
#define S_TIMES_C_D_KERNEL  "times_c_d_kernel"
#define N_TIMES_C_D_KERNEL 139
#define TIMES_C_CD_KERNEL  times_c_cd_kernel
#define S_TIMES_C_CD_KERNEL  "times_c_cd_kernel"
#define N_TIMES_C_CD_KERNEL 140
#define TIMES_D_F_KERNEL  times_d_f_kernel
#define S_TIMES_D_F_KERNEL  "times_d_f_kernel"
#define N_TIMES_D_F_KERNEL 141
#define TIMES_D_C_KERNEL  times_d_c_kernel
#define S_TIMES_D_C_KERNEL  "times_d_c_kernel"
#define N_TIMES_D_C_KERNEL 142
#define TIMES_D_D_KERNEL  times_d_d_kernel
#define S_TIMES_D_D_KERNEL  "times_d_d_kernel"
#define N_TIMES_D_D_KERNEL 143
#define TIMES_D_CD_KERNEL  times_d_cd_kernel
#define S_TIMES_D_CD_KERNEL  "times_d_cd_kernel"
#define N_TIMES_D_CD_KERNEL 144
#define TIMES_CD_F_KERNEL  times_cd_f_kernel
#define S_TIMES_CD_F_KERNEL  "times_cd_f_kernel"
#define N_TIMES_CD_F_KERNEL 145
#define TIMES_CD_C_KERNEL  times_cd_c_kernel
#define S_TIMES_CD_C_KERNEL  "times_cd_c_kernel"
#define N_TIMES_CD_C_KERNEL 146
#define TIMES_CD_D_KERNEL  times_cd_d_kernel
#define S_TIMES_CD_D_KERNEL  "times_cd_d_kernel"
#define N_TIMES_CD_D_KERNEL 147
#define TIMES_CD_CD_KERNEL  times_cd_cd_kernel
#define S_TIMES_CD_CD_KERNEL  "times_cd_cd_kernel"
#define N_TIMES_CD_CD_KERNEL 148
//
#define RDIVIDE_F_F_KERNEL  rdivide_f_f_kernel
#define S_RDIVIDE_F_F_KERNEL  "rdivide_f_f_kernel"
#define N_RDIVIDE_F_F_KERNEL 149
#define RDIVIDE_F_C_KERNEL  rdivide_f_c_kernel
#define S_RDIVIDE_F_C_KERNEL  "rdivide_f_c_kernel"
#define N_RDIVIDE_F_C_KERNEL 150
#define RDIVIDE_F_D_KERNEL  rdivide_f_d_kernel
#define S_RDIVIDE_F_D_KERNEL  "rdivide_f_d_kernel"
#define N_RDIVIDE_F_D_KERNEL 151
#define RDIVIDE_F_CD_KERNEL  rdivide_f_cd_kernel
#define S_RDIVIDE_F_CD_KERNEL  "rdivide_f_cd_kernel"
#define N_RDIVIDE_F_CD_KERNEL 152
#define RDIVIDE_C_F_KERNEL  rdivide_c_f_kernel
#define S_RDIVIDE_C_F_KERNEL  "rdivide_c_f_kernel"
#define N_RDIVIDE_C_F_KERNEL 153
#define RDIVIDE_C_C_KERNEL  rdivide_c_c_kernel
#define S_RDIVIDE_C_C_KERNEL  "rdivide_c_c_kernel"
#define N_RDIVIDE_C_C_KERNEL 154
#define RDIVIDE_C_D_KERNEL  rdivide_c_d_kernel
#define S_RDIVIDE_C_D_KERNEL  "rdivide_c_d_kernel"
#define N_RDIVIDE_C_D_KERNEL 155
#define RDIVIDE_C_CD_KERNEL  rdivide_c_cd_kernel
#define S_RDIVIDE_C_CD_KERNEL  "rdivide_c_cd_kernel"
#define N_RDIVIDE_C_CD_KERNEL 156
#define RDIVIDE_D_F_KERNEL  rdivide_d_f_kernel
#define S_RDIVIDE_D_F_KERNEL  "rdivide_d_f_kernel"
#define N_RDIVIDE_D_F_KERNEL 157
#define RDIVIDE_D_C_KERNEL  rdivide_d_c_kernel
#define S_RDIVIDE_D_C_KERNEL  "rdivide_d_c_kernel"
#define N_RDIVIDE_D_C_KERNEL 158
#define RDIVIDE_D_D_KERNEL  rdivide_d_d_kernel
#define S_RDIVIDE_D_D_KERNEL  "rdivide_d_d_kernel"
#define N_RDIVIDE_D_D_KERNEL 159
#define RDIVIDE_D_CD_KERNEL  rdivide_d_cd_kernel
#define S_RDIVIDE_D_CD_KERNEL  "rdivide_d_cd_kernel"
#define N_RDIVIDE_D_CD_KERNEL 160
#define RDIVIDE_CD_F_KERNEL  rdivide_cd_f_kernel
#define S_RDIVIDE_CD_F_KERNEL  "rdivide_cd_f_kernel"
#define N_RDIVIDE_CD_F_KERNEL 161
#define RDIVIDE_CD_C_KERNEL  rdivide_cd_c_kernel
#define S_RDIVIDE_CD_C_KERNEL  "rdivide_cd_c_kernel"
#define N_RDIVIDE_CD_C_KERNEL 162
#define RDIVIDE_CD_D_KERNEL  rdivide_cd_d_kernel
#define S_RDIVIDE_CD_D_KERNEL  "rdivide_cd_d_kernel"
#define N_RDIVIDE_CD_D_KERNEL 163
#define RDIVIDE_CD_CD_KERNEL  rdivide_cd_cd_kernel
#define S_RDIVIDE_CD_CD_KERNEL  "rdivide_cd_cd_kernel"
#define N_RDIVIDE_CD_CD_KERNEL 164
//
#define LDIVIDE_F_F_KERNEL  ldivide_f_f_kernel
#define S_LDIVIDE_F_F_KERNEL  "ldivide_f_f_kernel"
#define N_LDIVIDE_F_F_KERNEL 165
#define LDIVIDE_F_C_KERNEL  ldivide_f_c_kernel
#define S_LDIVIDE_F_C_KERNEL  "ldivide_f_c_kernel"
#define N_LDIVIDE_F_C_KERNEL 166
#define LDIVIDE_F_D_KERNEL  ldivide_f_d_kernel
#define S_LDIVIDE_F_D_KERNEL  "ldivide_f_d_kernel"
#define N_LDIVIDE_F_D_KERNEL 167
#define LDIVIDE_F_CD_KERNEL  ldivide_f_cd_kernel
#define S_LDIVIDE_F_CD_KERNEL  "ldivide_f_cd_kernel"
#define N_LDIVIDE_F_CD_KERNEL 168
#define LDIVIDE_C_F_KERNEL  ldivide_c_f_kernel
#define S_LDIVIDE_C_F_KERNEL  "ldivide_c_f_kernel"
#define N_LDIVIDE_C_F_KERNEL 169
#define LDIVIDE_C_C_KERNEL  ldivide_c_c_kernel
#define S_LDIVIDE_C_C_KERNEL  "ldivide_c_c_kernel"
#define N_LDIVIDE_C_C_KERNEL 170
#define LDIVIDE_C_D_KERNEL  ldivide_c_d_kernel
#define S_LDIVIDE_C_D_KERNEL  "ldivide_c_d_kernel"
#define N_LDIVIDE_C_D_KERNEL 171
#define LDIVIDE_C_CD_KERNEL  ldivide_c_cd_kernel
#define S_LDIVIDE_C_CD_KERNEL  "ldivide_c_cd_kernel"
#define N_LDIVIDE_C_CD_KERNEL 172
#define LDIVIDE_D_F_KERNEL  ldivide_d_f_kernel
#define S_LDIVIDE_D_F_KERNEL  "ldivide_d_f_kernel"
#define N_LDIVIDE_D_F_KERNEL 173
#define LDIVIDE_D_C_KERNEL  ldivide_d_c_kernel
#define S_LDIVIDE_D_C_KERNEL  "ldivide_d_c_kernel"
#define N_LDIVIDE_D_C_KERNEL 174
#define LDIVIDE_D_D_KERNEL  ldivide_d_d_kernel
#define S_LDIVIDE_D_D_KERNEL  "ldivide_d_d_kernel"
#define N_LDIVIDE_D_D_KERNEL 175
#define LDIVIDE_D_CD_KERNEL  ldivide_d_cd_kernel
#define S_LDIVIDE_D_CD_KERNEL  "ldivide_d_cd_kernel"
#define N_LDIVIDE_D_CD_KERNEL 176
#define LDIVIDE_CD_F_KERNEL  ldivide_cd_f_kernel
#define S_LDIVIDE_CD_F_KERNEL  "ldivide_cd_f_kernel"
#define N_LDIVIDE_CD_F_KERNEL 177
#define LDIVIDE_CD_C_KERNEL  ldivide_cd_c_kernel
#define S_LDIVIDE_CD_C_KERNEL  "ldivide_cd_c_kernel"
#define N_LDIVIDE_CD_C_KERNEL 178
#define LDIVIDE_CD_D_KERNEL  ldivide_cd_d_kernel
#define S_LDIVIDE_CD_D_KERNEL  "ldivide_cd_d_kernel"
#define N_LDIVIDE_CD_D_KERNEL 179
#define LDIVIDE_CD_CD_KERNEL  ldivide_cd_cd_kernel
#define S_LDIVIDE_CD_CD_KERNEL  "ldivide_cd_cd_kernel"
#define N_LDIVIDE_CD_CD_KERNEL 180
//
#define POWER_F_F_KERNEL  power_f_f_kernel
#define S_POWER_F_F_KERNEL  "power_f_f_kernel"
#define N_POWER_F_F_KERNEL 181
#define POWER_F_C_KERNEL  power_f_c_kernel
#define S_POWER_F_C_KERNEL  "power_f_c_kernel"
#define N_POWER_F_C_KERNEL 182
#define POWER_F_D_KERNEL  power_f_d_kernel
#define S_POWER_F_D_KERNEL  "power_f_d_kernel"
#define N_POWER_F_D_KERNEL 183
#define POWER_F_CD_KERNEL  power_f_cd_kernel
#define S_POWER_F_CD_KERNEL  "power_f_cd_kernel"
#define N_POWER_F_CD_KERNEL 184
#define POWER_C_F_KERNEL  power_c_f_kernel
#define S_POWER_C_F_KERNEL  "power_c_f_kernel"
#define N_POWER_C_F_KERNEL 185
#define POWER_C_C_KERNEL  power_c_c_kernel
#define S_POWER_C_C_KERNEL  "power_c_c_kernel"
#define N_POWER_C_C_KERNEL 186
#define POWER_C_D_KERNEL  power_c_d_kernel
#define S_POWER_C_D_KERNEL  "power_c_d_kernel"
#define N_POWER_C_D_KERNEL 187
#define POWER_C_CD_KERNEL  power_c_cd_kernel
#define S_POWER_C_CD_KERNEL  "power_c_cd_kernel"
#define N_POWER_C_CD_KERNEL 188
#define POWER_D_F_KERNEL  power_d_f_kernel
#define S_POWER_D_F_KERNEL  "power_d_f_kernel"
#define N_POWER_D_F_KERNEL 189
#define POWER_D_C_KERNEL  power_d_c_kernel
#define S_POWER_D_C_KERNEL  "power_d_c_kernel"
#define N_POWER_D_C_KERNEL 190
#define POWER_D_D_KERNEL  power_d_d_kernel
#define S_POWER_D_D_KERNEL  "power_d_d_kernel"
#define N_POWER_D_D_KERNEL 191
#define POWER_D_CD_KERNEL  power_d_cd_kernel
#define S_POWER_D_CD_KERNEL  "power_d_cd_kernel"
#define N_POWER_D_CD_KERNEL 192
#define POWER_CD_F_KERNEL  power_cd_f_kernel
#define S_POWER_CD_F_KERNEL  "power_cd_f_kernel"
#define N_POWER_CD_F_KERNEL 193
#define POWER_CD_C_KERNEL  power_cd_c_kernel
#define S_POWER_CD_C_KERNEL  "power_cd_c_kernel"
#define N_POWER_CD_C_KERNEL 194
#define POWER_CD_D_KERNEL  power_cd_d_kernel
#define S_POWER_CD_D_KERNEL  "power_cd_d_kernel"
#define N_POWER_CD_D_KERNEL 195
#define POWER_CD_CD_KERNEL  power_cd_cd_kernel
#define S_POWER_CD_CD_KERNEL  "power_cd_cd_kernel"
#define N_POWER_CD_CD_KERNEL 196
//
#define MINUS_F_F_KERNEL  minus_f_f_kernel
#define S_MINUS_F_F_KERNEL  "minus_f_f_kernel"
#define N_MINUS_F_F_KERNEL 197
#define MINUS_F_C_KERNEL  minus_f_c_kernel
#define S_MINUS_F_C_KERNEL  "minus_f_c_kernel"
#define N_MINUS_F_C_KERNEL 198
#define MINUS_F_D_KERNEL  minus_f_d_kernel
#define S_MINUS_F_D_KERNEL  "minus_f_d_kernel"
#define N_MINUS_F_D_KERNEL 199
#define MINUS_F_CD_KERNEL  minus_f_cd_kernel
#define S_MINUS_F_CD_KERNEL  "minus_f_cd_kernel"
#define N_MINUS_F_CD_KERNEL 200
#define MINUS_C_F_KERNEL  minus_c_f_kernel
#define S_MINUS_C_F_KERNEL  "minus_c_f_kernel"
#define N_MINUS_C_F_KERNEL 201
#define MINUS_C_C_KERNEL  minus_c_c_kernel
#define S_MINUS_C_C_KERNEL  "minus_c_c_kernel"
#define N_MINUS_C_C_KERNEL 202
#define MINUS_C_D_KERNEL  minus_c_d_kernel
#define S_MINUS_C_D_KERNEL  "minus_c_d_kernel"
#define N_MINUS_C_D_KERNEL 203
#define MINUS_C_CD_KERNEL  minus_c_cd_kernel
#define S_MINUS_C_CD_KERNEL  "minus_c_cd_kernel"
#define N_MINUS_C_CD_KERNEL 204
#define MINUS_D_F_KERNEL  minus_d_f_kernel
#define S_MINUS_D_F_KERNEL  "minus_d_f_kernel"
#define N_MINUS_D_F_KERNEL 205
#define MINUS_D_C_KERNEL  minus_d_c_kernel
#define S_MINUS_D_C_KERNEL  "minus_d_c_kernel"
#define N_MINUS_D_C_KERNEL 206
#define MINUS_D_D_KERNEL  minus_d_d_kernel
#define S_MINUS_D_D_KERNEL  "minus_d_d_kernel"
#define N_MINUS_D_D_KERNEL 207
#define MINUS_D_CD_KERNEL  minus_d_cd_kernel
#define S_MINUS_D_CD_KERNEL  "minus_d_cd_kernel"
#define N_MINUS_D_CD_KERNEL 208
#define MINUS_CD_F_KERNEL  minus_cd_f_kernel
#define S_MINUS_CD_F_KERNEL  "minus_cd_f_kernel"
#define N_MINUS_CD_F_KERNEL 209
#define MINUS_CD_C_KERNEL  minus_cd_c_kernel
#define S_MINUS_CD_C_KERNEL  "minus_cd_c_kernel"
#define N_MINUS_CD_C_KERNEL 210
#define MINUS_CD_D_KERNEL  minus_cd_d_kernel
#define S_MINUS_CD_D_KERNEL  "minus_cd_d_kernel"
#define N_MINUS_CD_D_KERNEL 211
#define MINUS_CD_CD_KERNEL  minus_cd_cd_kernel
#define S_MINUS_CD_CD_KERNEL  "minus_cd_cd_kernel"
#define N_MINUS_CD_CD_KERNEL 212
//
#define LT_F_F_KERNEL  lt_f_f_kernel
#define S_LT_F_F_KERNEL  "lt_f_f_kernel"
#define N_LT_F_F_KERNEL 213
#define LT_F_C_KERNEL  lt_f_c_kernel
#define S_LT_F_C_KERNEL  "lt_f_c_kernel"
#define N_LT_F_C_KERNEL 214
#define LT_F_D_KERNEL  lt_f_d_kernel
#define S_LT_F_D_KERNEL  "lt_f_d_kernel"
#define N_LT_F_D_KERNEL 215
#define LT_F_CD_KERNEL  lt_f_cd_kernel
#define S_LT_F_CD_KERNEL  "lt_f_cd_kernel"
#define N_LT_F_CD_KERNEL 216
#define LT_C_F_KERNEL  lt_c_f_kernel
#define S_LT_C_F_KERNEL  "lt_c_f_kernel"
#define N_LT_C_F_KERNEL 217
#define LT_C_C_KERNEL  lt_c_c_kernel
#define S_LT_C_C_KERNEL  "lt_c_c_kernel"
#define N_LT_C_C_KERNEL 218
#define LT_C_D_KERNEL  lt_c_d_kernel
#define S_LT_C_D_KERNEL  "lt_c_d_kernel"
#define N_LT_C_D_KERNEL 219
#define LT_C_CD_KERNEL  lt_c_cd_kernel
#define S_LT_C_CD_KERNEL  "lt_c_cd_kernel"
#define N_LT_C_CD_KERNEL 220
#define LT_D_F_KERNEL  lt_d_f_kernel
#define S_LT_D_F_KERNEL  "lt_d_f_kernel"
#define N_LT_D_F_KERNEL 221
#define LT_D_C_KERNEL  lt_d_c_kernel
#define S_LT_D_C_KERNEL  "lt_d_c_kernel"
#define N_LT_D_C_KERNEL 222
#define LT_D_D_KERNEL  lt_d_d_kernel
#define S_LT_D_D_KERNEL  "lt_d_d_kernel"
#define N_LT_D_D_KERNEL 223
#define LT_D_CD_KERNEL  lt_d_cd_kernel
#define S_LT_D_CD_KERNEL  "lt_d_cd_kernel"
#define N_LT_D_CD_KERNEL 224
#define LT_CD_F_KERNEL  lt_cd_f_kernel
#define S_LT_CD_F_KERNEL  "lt_cd_f_kernel"
#define N_LT_CD_F_KERNEL 225
#define LT_CD_C_KERNEL  lt_cd_c_kernel
#define S_LT_CD_C_KERNEL  "lt_cd_c_kernel"
#define N_LT_CD_C_KERNEL 226
#define LT_CD_D_KERNEL  lt_cd_d_kernel
#define S_LT_CD_D_KERNEL  "lt_cd_d_kernel"
#define N_LT_CD_D_KERNEL 227
#define LT_CD_CD_KERNEL  lt_cd_cd_kernel
#define S_LT_CD_CD_KERNEL  "lt_cd_cd_kernel"
#define N_LT_CD_CD_KERNEL 228
//
#define GT_F_F_KERNEL  gt_f_f_kernel
#define S_GT_F_F_KERNEL  "gt_f_f_kernel"
#define N_GT_F_F_KERNEL 229
#define GT_F_C_KERNEL  gt_f_c_kernel
#define S_GT_F_C_KERNEL  "gt_f_c_kernel"
#define N_GT_F_C_KERNEL 230
#define GT_F_D_KERNEL  gt_f_d_kernel
#define S_GT_F_D_KERNEL  "gt_f_d_kernel"
#define N_GT_F_D_KERNEL 231
#define GT_F_CD_KERNEL  gt_f_cd_kernel
#define S_GT_F_CD_KERNEL  "gt_f_cd_kernel"
#define N_GT_F_CD_KERNEL 232
#define GT_C_F_KERNEL  gt_c_f_kernel
#define S_GT_C_F_KERNEL  "gt_c_f_kernel"
#define N_GT_C_F_KERNEL 233
#define GT_C_C_KERNEL  gt_c_c_kernel
#define S_GT_C_C_KERNEL  "gt_c_c_kernel"
#define N_GT_C_C_KERNEL 234
#define GT_C_D_KERNEL  gt_c_d_kernel
#define S_GT_C_D_KERNEL  "gt_c_d_kernel"
#define N_GT_C_D_KERNEL 235
#define GT_C_CD_KERNEL  gt_c_cd_kernel
#define S_GT_C_CD_KERNEL  "gt_c_cd_kernel"
#define N_GT_C_CD_KERNEL 236
#define GT_D_F_KERNEL  gt_d_f_kernel
#define S_GT_D_F_KERNEL  "gt_d_f_kernel"
#define N_GT_D_F_KERNEL 237
#define GT_D_C_KERNEL  gt_d_c_kernel
#define S_GT_D_C_KERNEL  "gt_d_c_kernel"
#define N_GT_D_C_KERNEL 238
#define GT_D_D_KERNEL  gt_d_d_kernel
#define S_GT_D_D_KERNEL  "gt_d_d_kernel"
#define N_GT_D_D_KERNEL 239
#define GT_D_CD_KERNEL  gt_d_cd_kernel
#define S_GT_D_CD_KERNEL  "gt_d_cd_kernel"
#define N_GT_D_CD_KERNEL 240
#define GT_CD_F_KERNEL  gt_cd_f_kernel
#define S_GT_CD_F_KERNEL  "gt_cd_f_kernel"
#define N_GT_CD_F_KERNEL 241
#define GT_CD_C_KERNEL  gt_cd_c_kernel
#define S_GT_CD_C_KERNEL  "gt_cd_c_kernel"
#define N_GT_CD_C_KERNEL 242
#define GT_CD_D_KERNEL  gt_cd_d_kernel
#define S_GT_CD_D_KERNEL  "gt_cd_d_kernel"
#define N_GT_CD_D_KERNEL 243
#define GT_CD_CD_KERNEL  gt_cd_cd_kernel
#define S_GT_CD_CD_KERNEL  "gt_cd_cd_kernel"
#define N_GT_CD_CD_KERNEL 244
//
#define LE_F_F_KERNEL  le_f_f_kernel
#define S_LE_F_F_KERNEL  "le_f_f_kernel"
#define N_LE_F_F_KERNEL 245
#define LE_F_C_KERNEL  le_f_c_kernel
#define S_LE_F_C_KERNEL  "le_f_c_kernel"
#define N_LE_F_C_KERNEL 246
#define LE_F_D_KERNEL  le_f_d_kernel
#define S_LE_F_D_KERNEL  "le_f_d_kernel"
#define N_LE_F_D_KERNEL 247
#define LE_F_CD_KERNEL  le_f_cd_kernel
#define S_LE_F_CD_KERNEL  "le_f_cd_kernel"
#define N_LE_F_CD_KERNEL 248
#define LE_C_F_KERNEL  le_c_f_kernel
#define S_LE_C_F_KERNEL  "le_c_f_kernel"
#define N_LE_C_F_KERNEL 249
#define LE_C_C_KERNEL  le_c_c_kernel
#define S_LE_C_C_KERNEL  "le_c_c_kernel"
#define N_LE_C_C_KERNEL 250
#define LE_C_D_KERNEL  le_c_d_kernel
#define S_LE_C_D_KERNEL  "le_c_d_kernel"
#define N_LE_C_D_KERNEL 251
#define LE_C_CD_KERNEL  le_c_cd_kernel
#define S_LE_C_CD_KERNEL  "le_c_cd_kernel"
#define N_LE_C_CD_KERNEL 252
#define LE_D_F_KERNEL  le_d_f_kernel
#define S_LE_D_F_KERNEL  "le_d_f_kernel"
#define N_LE_D_F_KERNEL 253
#define LE_D_C_KERNEL  le_d_c_kernel
#define S_LE_D_C_KERNEL  "le_d_c_kernel"
#define N_LE_D_C_KERNEL 254
#define LE_D_D_KERNEL  le_d_d_kernel
#define S_LE_D_D_KERNEL  "le_d_d_kernel"
#define N_LE_D_D_KERNEL 255
#define LE_D_CD_KERNEL  le_d_cd_kernel
#define S_LE_D_CD_KERNEL  "le_d_cd_kernel"
#define N_LE_D_CD_KERNEL 256
#define LE_CD_F_KERNEL  le_cd_f_kernel
#define S_LE_CD_F_KERNEL  "le_cd_f_kernel"
#define N_LE_CD_F_KERNEL 257
#define LE_CD_C_KERNEL  le_cd_c_kernel
#define S_LE_CD_C_KERNEL  "le_cd_c_kernel"
#define N_LE_CD_C_KERNEL 258
#define LE_CD_D_KERNEL  le_cd_d_kernel
#define S_LE_CD_D_KERNEL  "le_cd_d_kernel"
#define N_LE_CD_D_KERNEL 259
#define LE_CD_CD_KERNEL  le_cd_cd_kernel
#define S_LE_CD_CD_KERNEL  "le_cd_cd_kernel"
#define N_LE_CD_CD_KERNEL 260
//
#define GE_F_F_KERNEL  ge_f_f_kernel
#define S_GE_F_F_KERNEL  "ge_f_f_kernel"
#define N_GE_F_F_KERNEL 261
#define GE_F_C_KERNEL  ge_f_c_kernel
#define S_GE_F_C_KERNEL  "ge_f_c_kernel"
#define N_GE_F_C_KERNEL 262
#define GE_F_D_KERNEL  ge_f_d_kernel
#define S_GE_F_D_KERNEL  "ge_f_d_kernel"
#define N_GE_F_D_KERNEL 263
#define GE_F_CD_KERNEL  ge_f_cd_kernel
#define S_GE_F_CD_KERNEL  "ge_f_cd_kernel"
#define N_GE_F_CD_KERNEL 264
#define GE_C_F_KERNEL  ge_c_f_kernel
#define S_GE_C_F_KERNEL  "ge_c_f_kernel"
#define N_GE_C_F_KERNEL 265
#define GE_C_C_KERNEL  ge_c_c_kernel
#define S_GE_C_C_KERNEL  "ge_c_c_kernel"
#define N_GE_C_C_KERNEL 266
#define GE_C_D_KERNEL  ge_c_d_kernel
#define S_GE_C_D_KERNEL  "ge_c_d_kernel"
#define N_GE_C_D_KERNEL 267
#define GE_C_CD_KERNEL  ge_c_cd_kernel
#define S_GE_C_CD_KERNEL  "ge_c_cd_kernel"
#define N_GE_C_CD_KERNEL 268
#define GE_D_F_KERNEL  ge_d_f_kernel
#define S_GE_D_F_KERNEL  "ge_d_f_kernel"
#define N_GE_D_F_KERNEL 269
#define GE_D_C_KERNEL  ge_d_c_kernel
#define S_GE_D_C_KERNEL  "ge_d_c_kernel"
#define N_GE_D_C_KERNEL 270
#define GE_D_D_KERNEL  ge_d_d_kernel
#define S_GE_D_D_KERNEL  "ge_d_d_kernel"
#define N_GE_D_D_KERNEL 271
#define GE_D_CD_KERNEL  ge_d_cd_kernel
#define S_GE_D_CD_KERNEL  "ge_d_cd_kernel"
#define N_GE_D_CD_KERNEL 272
#define GE_CD_F_KERNEL  ge_cd_f_kernel
#define S_GE_CD_F_KERNEL  "ge_cd_f_kernel"
#define N_GE_CD_F_KERNEL 273
#define GE_CD_C_KERNEL  ge_cd_c_kernel
#define S_GE_CD_C_KERNEL  "ge_cd_c_kernel"
#define N_GE_CD_C_KERNEL 274
#define GE_CD_D_KERNEL  ge_cd_d_kernel
#define S_GE_CD_D_KERNEL  "ge_cd_d_kernel"
#define N_GE_CD_D_KERNEL 275
#define GE_CD_CD_KERNEL  ge_cd_cd_kernel
#define S_GE_CD_CD_KERNEL  "ge_cd_cd_kernel"
#define N_GE_CD_CD_KERNEL 276
//
#define NE_F_F_KERNEL  ne_f_f_kernel
#define S_NE_F_F_KERNEL  "ne_f_f_kernel"
#define N_NE_F_F_KERNEL 277
#define NE_F_C_KERNEL  ne_f_c_kernel
#define S_NE_F_C_KERNEL  "ne_f_c_kernel"
#define N_NE_F_C_KERNEL 278
#define NE_F_D_KERNEL  ne_f_d_kernel
#define S_NE_F_D_KERNEL  "ne_f_d_kernel"
#define N_NE_F_D_KERNEL 279
#define NE_F_CD_KERNEL  ne_f_cd_kernel
#define S_NE_F_CD_KERNEL  "ne_f_cd_kernel"
#define N_NE_F_CD_KERNEL 280
#define NE_C_F_KERNEL  ne_c_f_kernel
#define S_NE_C_F_KERNEL  "ne_c_f_kernel"
#define N_NE_C_F_KERNEL 281
#define NE_C_C_KERNEL  ne_c_c_kernel
#define S_NE_C_C_KERNEL  "ne_c_c_kernel"
#define N_NE_C_C_KERNEL 282
#define NE_C_D_KERNEL  ne_c_d_kernel
#define S_NE_C_D_KERNEL  "ne_c_d_kernel"
#define N_NE_C_D_KERNEL 283
#define NE_C_CD_KERNEL  ne_c_cd_kernel
#define S_NE_C_CD_KERNEL  "ne_c_cd_kernel"
#define N_NE_C_CD_KERNEL 284
#define NE_D_F_KERNEL  ne_d_f_kernel
#define S_NE_D_F_KERNEL  "ne_d_f_kernel"
#define N_NE_D_F_KERNEL 285
#define NE_D_C_KERNEL  ne_d_c_kernel
#define S_NE_D_C_KERNEL  "ne_d_c_kernel"
#define N_NE_D_C_KERNEL 286
#define NE_D_D_KERNEL  ne_d_d_kernel
#define S_NE_D_D_KERNEL  "ne_d_d_kernel"
#define N_NE_D_D_KERNEL 287
#define NE_D_CD_KERNEL  ne_d_cd_kernel
#define S_NE_D_CD_KERNEL  "ne_d_cd_kernel"
#define N_NE_D_CD_KERNEL 288
#define NE_CD_F_KERNEL  ne_cd_f_kernel
#define S_NE_CD_F_KERNEL  "ne_cd_f_kernel"
#define N_NE_CD_F_KERNEL 289
#define NE_CD_C_KERNEL  ne_cd_c_kernel
#define S_NE_CD_C_KERNEL  "ne_cd_c_kernel"
#define N_NE_CD_C_KERNEL 290
#define NE_CD_D_KERNEL  ne_cd_d_kernel
#define S_NE_CD_D_KERNEL  "ne_cd_d_kernel"
#define N_NE_CD_D_KERNEL 291
#define NE_CD_CD_KERNEL  ne_cd_cd_kernel
#define S_NE_CD_CD_KERNEL  "ne_cd_cd_kernel"
#define N_NE_CD_CD_KERNEL 292
//
#define EQ_F_F_KERNEL  eq_f_f_kernel
#define S_EQ_F_F_KERNEL  "eq_f_f_kernel"
#define N_EQ_F_F_KERNEL 293
#define EQ_F_C_KERNEL  eq_f_c_kernel
#define S_EQ_F_C_KERNEL  "eq_f_c_kernel"
#define N_EQ_F_C_KERNEL 294
#define EQ_F_D_KERNEL  eq_f_d_kernel
#define S_EQ_F_D_KERNEL  "eq_f_d_kernel"
#define N_EQ_F_D_KERNEL 295
#define EQ_F_CD_KERNEL  eq_f_cd_kernel
#define S_EQ_F_CD_KERNEL  "eq_f_cd_kernel"
#define N_EQ_F_CD_KERNEL 296
#define EQ_C_F_KERNEL  eq_c_f_kernel
#define S_EQ_C_F_KERNEL  "eq_c_f_kernel"
#define N_EQ_C_F_KERNEL 297
#define EQ_C_C_KERNEL  eq_c_c_kernel
#define S_EQ_C_C_KERNEL  "eq_c_c_kernel"
#define N_EQ_C_C_KERNEL 298
#define EQ_C_D_KERNEL  eq_c_d_kernel
#define S_EQ_C_D_KERNEL  "eq_c_d_kernel"
#define N_EQ_C_D_KERNEL 299
#define EQ_C_CD_KERNEL  eq_c_cd_kernel
#define S_EQ_C_CD_KERNEL  "eq_c_cd_kernel"
#define N_EQ_C_CD_KERNEL 300
#define EQ_D_F_KERNEL  eq_d_f_kernel
#define S_EQ_D_F_KERNEL  "eq_d_f_kernel"
#define N_EQ_D_F_KERNEL 301
#define EQ_D_C_KERNEL  eq_d_c_kernel
#define S_EQ_D_C_KERNEL  "eq_d_c_kernel"
#define N_EQ_D_C_KERNEL 302
#define EQ_D_D_KERNEL  eq_d_d_kernel
#define S_EQ_D_D_KERNEL  "eq_d_d_kernel"
#define N_EQ_D_D_KERNEL 303
#define EQ_D_CD_KERNEL  eq_d_cd_kernel
#define S_EQ_D_CD_KERNEL  "eq_d_cd_kernel"
#define N_EQ_D_CD_KERNEL 304
#define EQ_CD_F_KERNEL  eq_cd_f_kernel
#define S_EQ_CD_F_KERNEL  "eq_cd_f_kernel"
#define N_EQ_CD_F_KERNEL 305
#define EQ_CD_C_KERNEL  eq_cd_c_kernel
#define S_EQ_CD_C_KERNEL  "eq_cd_c_kernel"
#define N_EQ_CD_C_KERNEL 306
#define EQ_CD_D_KERNEL  eq_cd_d_kernel
#define S_EQ_CD_D_KERNEL  "eq_cd_d_kernel"
#define N_EQ_CD_D_KERNEL 307
#define EQ_CD_CD_KERNEL  eq_cd_cd_kernel
#define S_EQ_CD_CD_KERNEL  "eq_cd_cd_kernel"
#define N_EQ_CD_CD_KERNEL 308
//
#define AND_F_F_KERNEL  and_f_f_kernel
#define S_AND_F_F_KERNEL  "and_f_f_kernel"
#define N_AND_F_F_KERNEL 309
#define N_AND_F_C_KERNEL -1
#define AND_F_D_KERNEL  and_f_d_kernel
#define S_AND_F_D_KERNEL  "and_f_d_kernel"
#define N_AND_F_D_KERNEL 310
#define N_AND_F_CD_KERNEL -1
#define N_AND_C_F_KERNEL -1
#define N_AND_C_C_KERNEL -1
#define N_AND_C_D_KERNEL -1
#define N_AND_C_CD_KERNEL -1
#define AND_D_F_KERNEL  and_d_f_kernel
#define S_AND_D_F_KERNEL  "and_d_f_kernel"
#define N_AND_D_F_KERNEL 311
#define N_AND_D_C_KERNEL -1
#define AND_D_D_KERNEL  and_d_d_kernel
#define S_AND_D_D_KERNEL  "and_d_d_kernel"
#define N_AND_D_D_KERNEL 312
#define N_AND_D_CD_KERNEL -1
#define N_AND_CD_F_KERNEL -1
#define N_AND_CD_C_KERNEL -1
#define N_AND_CD_D_KERNEL -1
#define N_AND_CD_CD_KERNEL -1
//
#define OR_F_F_KERNEL  or_f_f_kernel
#define S_OR_F_F_KERNEL  "or_f_f_kernel"
#define N_OR_F_F_KERNEL 313
#define N_OR_F_C_KERNEL -1
#define OR_F_D_KERNEL  or_f_d_kernel
#define S_OR_F_D_KERNEL  "or_f_d_kernel"
#define N_OR_F_D_KERNEL 314
#define N_OR_F_CD_KERNEL -1
#define N_OR_C_F_KERNEL -1
#define N_OR_C_C_KERNEL -1
#define N_OR_C_D_KERNEL -1
#define N_OR_C_CD_KERNEL -1
#define OR_D_F_KERNEL  or_d_f_kernel
#define S_OR_D_F_KERNEL  "or_d_f_kernel"
#define N_OR_D_F_KERNEL 315
#define N_OR_D_C_KERNEL -1
#define OR_D_D_KERNEL  or_d_d_kernel
#define S_OR_D_D_KERNEL  "or_d_d_kernel"
#define N_OR_D_D_KERNEL 316
#define N_OR_D_CD_KERNEL -1
#define N_OR_CD_F_KERNEL -1
#define N_OR_CD_C_KERNEL -1
#define N_OR_CD_D_KERNEL -1
#define N_OR_CD_CD_KERNEL -1
//
#define FMAX_F_F_KERNEL  fmax_f_f_kernel
#define S_FMAX_F_F_KERNEL  "fmax_f_f_kernel"
#define N_FMAX_F_F_KERNEL 317
#define N_FMAX_F_C_KERNEL -1
#define FMAX_F_D_KERNEL  fmax_f_d_kernel
#define S_FMAX_F_D_KERNEL  "fmax_f_d_kernel"
#define N_FMAX_F_D_KERNEL 318
#define N_FMAX_F_CD_KERNEL -1
#define N_FMAX_C_F_KERNEL -1
#define N_FMAX_C_C_KERNEL -1
#define N_FMAX_C_D_KERNEL -1
#define N_FMAX_C_CD_KERNEL -1
#define FMAX_D_F_KERNEL  fmax_d_f_kernel
#define S_FMAX_D_F_KERNEL  "fmax_d_f_kernel"
#define N_FMAX_D_F_KERNEL 319
#define N_FMAX_D_C_KERNEL -1
#define FMAX_D_D_KERNEL  fmax_d_d_kernel
#define S_FMAX_D_D_KERNEL  "fmax_d_d_kernel"
#define N_FMAX_D_D_KERNEL 320
#define N_FMAX_D_CD_KERNEL -1
#define N_FMAX_CD_F_KERNEL -1
#define N_FMAX_CD_C_KERNEL -1
#define N_FMAX_CD_D_KERNEL -1
#define N_FMAX_CD_CD_KERNEL -1
//
#define FMIN_F_F_KERNEL  fmin_f_f_kernel
#define S_FMIN_F_F_KERNEL  "fmin_f_f_kernel"
#define N_FMIN_F_F_KERNEL 321
#define N_FMIN_F_C_KERNEL -1
#define FMIN_F_D_KERNEL  fmin_f_d_kernel
#define S_FMIN_F_D_KERNEL  "fmin_f_d_kernel"
#define N_FMIN_F_D_KERNEL 322
#define N_FMIN_F_CD_KERNEL -1
#define N_FMIN_C_F_KERNEL -1
#define N_FMIN_C_C_KERNEL -1
#define N_FMIN_C_D_KERNEL -1
#define N_FMIN_C_CD_KERNEL -1
#define FMIN_D_F_KERNEL  fmin_d_f_kernel
#define S_FMIN_D_F_KERNEL  "fmin_d_f_kernel"
#define N_FMIN_D_F_KERNEL 323
#define N_FMIN_D_C_KERNEL -1
#define FMIN_D_D_KERNEL  fmin_d_d_kernel
#define S_FMIN_D_D_KERNEL  "fmin_d_d_kernel"
#define N_FMIN_D_D_KERNEL 324
#define N_FMIN_D_CD_KERNEL -1
#define N_FMIN_CD_F_KERNEL -1
#define N_FMIN_CD_C_KERNEL -1
#define N_FMIN_CD_D_KERNEL -1
#define N_FMIN_CD_CD_KERNEL -1
