% cublasError - Returns a structure with CUBLAS result codes
% 
% DESCRIPTION
% Returns a structure with CUBLAS result codes.
% 
% EXAMPLE
% 
% cublasError
% 
% ans =
% 
% CUBLAS_STATUS_SUCCESS: 0
% CUBLAS_STATUS_NOT_INITIALIZED: 1
% CUBLAS_STATUS_ALLOC_FAILED: 3
% CUBLAS_STATUS_INVALID_VALUE: 7
% CUBLAS_STATUS_ARCH_MISMATCH: 8
% CUBLAS_STATUS_MAPPING_ERROR: 11
% CUBLAS_STATUS_EXECUTION_FAILED: 13
% CUBLAS_STATUS_INTERNAL_ERROR: 14
